language: rust
cache: cargo
script: cargo build --release
deploy:
  - provider: releases
    edge: true
    api_key:
      secure: UbNKfxJZBTsI+5WDQqte8L4vAukNw6BUUISXKJGoo/RMSY//eAepYdOD+ffb4LJEYXKqNqbr+jOFj5lP17fzflbwHso5EYnR29p+6mEQXK+nfQJsroAxJg+NcBLjcnevUZiB94+Ao5QSXoPWX8CPOcLqT04BgKqjn/8M2pzxkdD4rMuLmCxAbK+7UWpQ/iB5JDcN2TEelvkFuFWG+GR1NXGe9k3/pI+QWsBMzfUtSdqS/MMDvr6sCkjdHxk05NjxTOpOa9G4V/mrb5PaVvZYJf/PCgdPEdwYLcX+mP3gz8EieVA0CNzhQx59oqOui2Wfblk7uMUIJOvsAj0VcD/8LItIHxa4mz82VRWlitlCnvMoybO3bsTW3rkFrfts3iZMgCPuBOAk7ehOruwsbN3wKTVHowAd7h44R5aLOe9hsgexNekr9MsbBDH7p+TMttIiUD7GUJrK4njVG0x0Bcq+BvT30sSkXcmx6IW0gwQPlwCX9pO5gs4h1xjEW47b+knd5bgZMrySGkXFyydi2YuPyi3t0a6UnFJINvBJ9llYcqAnjFQZQcTKk7/Kftcl082re9F9Hnjl4yx3r0rAz90wFI4LGrn/ml2dUg4FslFARgcTywr4wxo7iWGXQ5KfWhN9bIrg8ND7w0jtOmmQoky7UwXs3Hf/8M+Ms+/h0kKDRF4=
    file: ./target/release/milcheck
    on:
      repo: doums/milcheck
      tags: true
